### ISSUE TITLE
after start  gitbook-server in docker, unable to find a option that creates a gitbook

### ISSUE THREAD

**Issue by liuxx532** [tobegit3hub/gitbook-server#6]
In order to start gitbook-server in docker, I added two empty files in "gitbook" dir, and use "gitbook serve" to start the server.

![image](https://cloud.githubusercontent.com/assets/12507976/11864781/7af47f8c-a4da-11e5-8f50-dd286dac09f2.png)

## However, when I open the index page, I find there is no way to create a BOOK !!! (that's wired)

![image](https://cloud.githubusercontent.com/assets/12507976/11864703/ed28028c-a4d9-11e5-9e75-38a7e5229b5a.png)

> Hopefully, the information is enough to help you guys understand me.
So please tell me what kind of mistakes I had DONE, or what else I need to do. 
Thanks for your Patient.

**Comment by tobegit3hub** [comment]
Thanks @liuxx532 for reporting. This project is for github server but not for gitbook.com. So we have to create the files of gitbook project before and could not create the gitbook in its Web UI.

I hope this could help. @liuxx532
